# Ejercicio 1
**Matrices:**
A = [[1, 2], [3, 4]]
B = [[2, 0], [1, 2]]

- Calcula A + B, A - B y el producto matricial A × B.
- Calcula la traspuesta de A y la inversa de B (si existe).

**Vectores:**
u = [1, 2]
v = [3, -1]
- Calcula el producto interno u·v.
- Calcula la magnitud de cada vector.

**Derivadas:**
f(x) = x3 + 2*x2 + x
- Calcula la derivada primera y segunda de f(x).
- Evalúa ambas derivadas en x = 1. """

In [95]:
import numpy as np
import sympy as sp

# MATRICES
print("\n" + "="*50 + " \nMATRICES " + "\n" + "="*50)

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

suma_matriz = A + B
print(F"Suma de Matriz \n{suma_matriz}")

resta_matriz = A -B
print(f"\nResta de Matrices: \n{resta_matriz}")

producto_matricial = np.dot(A, B)
print(f"\nProducto Matricial: \n{producto_matricial}")

transpuesta_A = A.T
print(f"\nTranspuesta de A: \n{transpuesta_A}")

print(f"\nInversa de B")
try:
    inversa_B = np.linalg.inv(B)
    print(inversa_B)
except:
    print("No existe inversa (determinante = 0)")

# VECTORES
print("\n" + "="*50 + " \nVECTORES " + "\n" + "="*50)

u = np.array([1, 2]) 
v = np.array([3, -1])

# Producto interno
producto_interno = np.dot(u, v)
print(f"\nEl produccto interno entre u y v es {producto_interno}")

# Magnitud del vector U
magnitud_u = np.linalg.norm(u)
print(f"\nLa magnitud del vector u es {magnitud_u}")

# Magnitud del vector v
magnitud_v = np.linalg.norm(v)
print(f"\nLa magnitud del vector v es {magnitud_v}")

# DERIVADAS
print("\n" + "="*50 + " \nDERIVADAS " + "\n" + "="*50)

x = sp.symbols('x')
f = x**3 + 2*x**2 + x
print("F(x) =", f)

# Primera Derivada f'(x) = [x3 + 2*x2 + x]'
df = sp.diff(f, x)
print("\ndf/dx =", df)

# Segunda Derivada f''(x) = [x3 + 2*x2 + x]'
d2f = sp.diff(f, x, 2)
print("\nd²f/dx² =", d2f)

print(f"\nEvaluación de x=1 en:")
# Evaluación de x=1 en la primera derivada
print(f"f'(1) = {df.subs(x, 1)}") 

# Evaluación de x=1 en la segunda derivada

print(f"f''(1) = {d2f.subs(x, 1)}")


MATRICES 
Suma de Matriz 
[[3 2]
 [4 6]]

Resta de Matrices: 
[[-1  2]
 [ 2  2]]

Producto Matricial: 
[[ 4  4]
 [10  8]]

Transpuesta de A: 
[[1 3]
 [2 4]]

Inversa de B
[[ 0.5   0.  ]
 [-0.25  0.5 ]]

VECTORES 

El produccto interno entre u y v es 1

La magnitud del vector u es 2.23606797749979

La magnitud del vector v es 3.1622776601683795

DERIVADAS 
F(x) = x**3 + 2*x**2 + x

df/dx = 3*x**2 + 4*x + 1

d²f/dx² = 2*(3*x + 2)

Evaluación de x=1 en:
f'(1) = 8
f''(1) = 10
